### ISSUE TITLE
TODO Ideen-App

### ISSUE THREAD

**Issue by moritz2104** [Socialee/socialee#71]
- [ ] wenn user bekannt aber nicht angemeldet: passwort-field zeigen und user direkt im review-screen anmelden
- [x] unangemeldete User müssen bei klick auf Herz weitergeleitet oder gefragt werden, ob sie sich anmelden möchten
- [x] liken mit Kommentarfunktion
- [x] jQuery für Karten-Umdrehen, auf Rückseite werden Kommentare angezeigt
- [x]  font-awesome wird nicht zuverlässig geladen
- [x] show featured ideas only on landingpage (models um featured erweitern)
- [x] styling für nicht-veröffentlichte anpassen
- [x] Karten hüpfen beim Laden
- [ ]
